substitutions:
  aht20_temp_offset: "0"
  bmp280_temp_offset: "0"

sensor:
  - platform: aht10
    variant: AHT20
    i2c_id: i2c_bus
    address: ${aht20_address}
    temperature:
      name: "AHT20 Temperature"
      filters:
        - offset: ${aht20_temp_offset}
    humidity:
      name: "AHT20 Humidity"
    update_interval: ${update_interval}
  - platform: bmp280_i2c
    i2c_id: i2c_bus
    address: ${bmp280_address}
    temperature:
      name: "BMP280 Temperature"
      filters:
        - offset: ${bmp280_temp_offset}
    pressure:
      name: "BMP280 Pressure"
    update_interval: ${update_interval}
