esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

packages:
  wifi: !include .wifi.yaml

logger:
  level: INFO
  logs:
    component: ERROR
    sensor: WARN
  on_message:
    level: DEBUG
    then:
      - homeassistant.action:
          action: system_log.write
          data:
            level: !lambda |-
              switch (level) {
                case 0:
                  return "notset";
                case 1:
                  return "error";
                case 2:
                  return "warning";
                case 3:
                  return "info";
              }
              return "debug";
            logger: !lambda |-
              return "esphome.${device_name}";
            message: !lambda |-
              return message;

button:
  - platform: restart
    id: restart_device
    entity_category: config
    name: "Restart"