packages:
  board: !include ../boards/.dev.yaml
  bt: !include ../common/.bt.yaml
  i2c: !include ../components/.i2c.yaml
  bh1750: !include ../components/.bh1750.yaml
  aht20-bmp280: !include ../components/.aht20-bmp280.yaml
esp32:
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"

status_led:
  pin: GPIO2
