packages:
  board: !include ../boards/.m5stack-atom-lite.yaml

external_components:
  - source:
      type: git
      url: https://github.com/SleepinDevil/esphome-powerpal_ble.git
    components: [ powerpal_ble ]
    refresh: 1d

# optional requirement used with daily energy sensor
time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:

ble_client:
  - mac_address: ${ble_client_mac_address}
    id: powerpal

sensor:
  - platform: powerpal_ble
    ble_client_id: powerpal
    power:
      name: "Powerpal Power"
      accuracy_decimals: 0
    daily_energy:
      name: "Powerpal Daily Energy"
    energy:
      name: "Powerpal Total Energy"
      accuracy_decimals: 3
    battery_level:
      name: "Powerpal Battery"
    pairing_code: ${ble_pairing_code}
    notification_interval: 1 # get updates every 1 minute
    pulses_per_kwh: 1000
    time_id: homeassistant_time # daily energy still works without a time_id, but recommended to include one to properly handle daylight savings, etc.