packages:
  board: !include {
    file: packages/boards/.dev.yaml,
    vars: {
      device_name: dev-test,
      device_friendly_name: dev-test
    }
  }
  aht20-bmp280: !include {
    file: packages/components/.aht20-bmp280.yaml,
    vars: {
      i2c_sda: 21,
      i2c_scl: 22,
      aht20_address: 0x38,
      bmp280_address: 0x77,
      update_interval: 60s
    }
  }

esp32:
  framework: 
    type: esp-idf