packages:
  device: !include {
    file: packages/devices/.luminance.yaml,
    vars: {
      device_name: living-room-luminance,
      device_friendly_name: living-room-luminance,
      i2c_sda: 21,
      i2c_scl: 22,
      i2c_address: 0x23,
      update_interval: 30s
    }
  }