packages:
  wifi: !include packages/common/.wifi-iot.yaml
  garage-door:
    !include {
      file: packages/devices/.garage-door-rf.yaml,
      vars:
        {
          device_name: testbench,
          device_friendly_name: Testbench,
          cc1101_cs: GPIO5,
          cc1101_gdo0: GPIO4,
          cc1101_gdo2: GPIO16,
          spi_clk: GPIO18,
          spi_mosi: GPIO23,
          spi_miso: GPIO19,
        },
    }
  debug-log: !include { file: packages/debug/.log.yaml }
