substitutions:
  device_name: testbench
  device_friendly_name: testbench

packages:
  wifi: !include packages/common/.wifi-iot.yaml
  vent-controller:
    !include {
      file: packages/devices/.x1c-chamber-vent-controller.yaml,
      vars:
        {
          device_name: testbench,
          device_friendly_name: testbench,
          motor_a_in1: GPIO16,
          motor_a_in2: GPIO17,
          motor_b_in3: GPIO18,
          motor_b_in4: GPIO19,
        },
    }
  debug-log: !include { file: packages/debug/.log.yaml }
